#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

public static partial class AssetAccessorGenerator
{
  public static class AudioAccessor
  {
    public static void Generate(string assetPath, string outputPath)
    {
      var directory = Path.GetDirectoryName(outputPath);
      if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
      {
        _ = Directory.CreateDirectory(directory);
      }

      var sb = new StringBuilder();

      _ = sb.AppendLine("// <auto-generated />");
      _ = sb.AppendLine("// This file is generated by AssetAccessorGenerator.AudioAccessor. Do not edit manually.");
      _ = sb.AppendLine("using UnityEngine;");
      _ = sb.AppendLine();
      _ = sb.AppendLine("public static partial class AssetAccessor");
      _ = sb.AppendLine("{");

      GenerateAudioPart(sb, assetPath);

      _ = sb.AppendLine("}");

      File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
      AssetDatabase.Refresh();

      Console.WriteLine($"[AssetAccessorGenerator.AudioAccessor] Generated: {outputPath}");
    }

    private static void GenerateAudioPart(StringBuilder sb, string assetPath)
    {
      _ = sb.AppendLine("  public static partial class Audio");
      _ = sb.AppendLine("  {");

      GenerateAudioSEPart(sb, assetPath);

      _ = sb.AppendLine("  }");
    }

    private static void GenerateAudioSEPart(StringBuilder sb, string seDir)
    {
      var seEnumItems = new (string enumName, string resPath)[0];

      if (Directory.Exists(seDir))
      {
        var guids = AssetDatabase.FindAssets("t:AudioClip", new[] { seDir });
        seEnumItems = guids
          .Select(guid =>
          {
            var assetPath = AssetDatabase.GUIDToAssetPath(guid);
            var withoutExt = Path.ChangeExtension(assetPath, null);
            var idx = withoutExt.IndexOf("Resources/", StringComparison.Ordinal);
            var resPath = withoutExt[(idx + "Resources/".Length)..].Replace("\\", "/");
            var name = Path.GetFileName(withoutExt);
            var enumName = MakeSafeName(name);
            return (enumName, resPath);
          })
          .Distinct()
          .OrderBy(x => x.enumName)
          .ToArray();
      }

      _ = sb.AppendLine("    public static partial class SE");
      _ = sb.AppendLine("    {");
      _ = sb.AppendLine("      public enum Id");
      _ = sb.AppendLine("      {");

      if (seEnumItems.Length == 0)
      {
        _ = sb.AppendLine("        // No SE clips found");
      }

      foreach (var (enumName, _) in seEnumItems)
      {
        _ = sb.AppendLine($"        {enumName},");
      }

      _ = sb.AppendLine("      }");
      _ = sb.AppendLine();

      foreach (var (enumName, _) in seEnumItems)
      {
        _ = sb.AppendLine($"      public static class {enumName}");
        _ = sb.AppendLine("      {");
        _ = sb.AppendLine($"        private static Id Enum => Id.{enumName};");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        public static AudioClip Load() => AssetAccessor.Audio.SE.Load(Enum);");
        _ = sb.AppendLine("      }");
        _ = sb.AppendLine();
      }

      _ = sb.AppendLine("      private static string Path(Id id)");
      _ = sb.AppendLine("      {");
      _ = sb.AppendLine("        switch (id)");
      _ = sb.AppendLine("        {");
      foreach (var (enumName, resPath) in seEnumItems)
      {
        _ = sb.AppendLine($"          case Id.{enumName}: return \"{resPath}\";");
      }

      _ = sb.AppendLine("          default: throw new System.ArgumentOutOfRangeException(nameof(id), id, null);");
      _ = sb.AppendLine("        }");
      _ = sb.AppendLine("      }");

      _ = sb.AppendLine("    }");
    }

    private static string MakeSafeName(string name)
    {
      if (string.IsNullOrEmpty(name)) return "_";

      var sb = new StringBuilder(name.Length);
      bool upperNext = true;

      foreach (var ch in name)
      {
        if (char.IsLetterOrDigit(ch))
        {
          _ = sb.Append(upperNext ? char.ToUpperInvariant(ch) : ch);
          upperNext = false;
        }
        else
        {
          upperNext = true;
        }
      }

      if (sb.Length == 0) _ = sb.Append("_");
      if (char.IsDigit(sb[0])) _ = sb.Insert(0, '_');
      return sb.ToString();
    }
  }
}
#endif
