#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

public static partial class AssetAccessorGenerator
{
  public static class SceneAccessor
  {
    public static void Generate(string outputPath)
    {
      var directory = Path.GetDirectoryName(outputPath);
      if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
      {
        _ = Directory.CreateDirectory(directory);
      }

      var sb = new StringBuilder();

      _ = sb.AppendLine("// <auto-generated />");
      _ = sb.AppendLine("// This file is generated by AssetAccessorGenerator.SceneAccessor. Do not edit manually.");
      _ = sb.AppendLine("using UnityEngine;");
      _ = sb.AppendLine("using UnityEngine.SceneManagement;");
      _ = sb.AppendLine();
      _ = sb.AppendLine("public static partial class AssetAccessor");
      _ = sb.AppendLine("{");

      GenerateScenePart(sb);

      _ = sb.AppendLine("}");

      File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
      AssetDatabase.Refresh();

      Console.WriteLine($"[AssetAccessorGenerator.SceneAccessor] Generated: {outputPath}");
    }

    private static void GenerateScenePart(StringBuilder sb)
    {
      var scenes = EditorBuildSettings.scenes
        .Where(s => s.enabled)
        .ToArray();

      _ = sb.AppendLine("  public static partial class Scene");
      _ = sb.AppendLine("  {");

      if (scenes.Length == 0)
      {
        _ = sb.AppendLine("    // No scenes in build settings.");
        _ = sb.AppendLine("  }");
        return;
      }

      _ = sb.AppendLine("    public enum Id");
      _ = sb.AppendLine("    {");
      foreach (var scene in scenes)
      {
        var name = Path.GetFileNameWithoutExtension(scene.path);
        var enumName = MakeSafeName(name);
        _ = sb.AppendLine($"      {enumName},");
      }

      _ = sb.AppendLine("    }");
      _ = sb.AppendLine();

      foreach (var scene in scenes)
      {
        var name = Path.GetFileNameWithoutExtension(scene.path);
        var enumName = MakeSafeName(name);

        _ = sb.AppendLine($"    public static partial class {enumName}");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine($"      private static Id Enum => Id.{enumName};");
        _ = sb.AppendLine("      public static void Load() => AssetAccessor.Scene.Load(Enum);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
      }

      _ = sb.AppendLine("    internal static string Path(Id id)");
      _ = sb.AppendLine("    {");
      _ = sb.AppendLine("      switch (id)");
      _ = sb.AppendLine("      {");
      foreach (var scene in scenes)
      {
        var name = Path.GetFileNameWithoutExtension(scene.path);
        var enumName = MakeSafeName(name);
        var path = scene.path.Replace("\\", "/");
        _ = sb.AppendLine($"        case Id.{enumName}: return \"{path}\";");
      }

      _ = sb.AppendLine("        default: throw new System.ArgumentOutOfRangeException(nameof(id), id, null);");
      _ = sb.AppendLine("      }");
      _ = sb.AppendLine("    }");

      _ = sb.AppendLine("  }");
    }

    private static string MakeSafeName(string name)
    {
      if (string.IsNullOrEmpty(name)) return "_";

      var sb = new StringBuilder(name.Length);
      bool upperNext = true;

      foreach (var ch in name)
      {
        if (char.IsLetterOrDigit(ch))
        {
          _ = sb.Append(upperNext ? char.ToUpperInvariant(ch) : ch);
          upperNext = false;
        }
        else
        {
          upperNext = true;
        }
      }

      if (sb.Length == 0) _ = sb.Append("_");
      if (char.IsDigit(sb[0])) _ = sb.Insert(0, '_');
      return sb.ToString();
    }
  }
}
#endif
